apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-cicd
spec:
  selector:
    matchLabels:
      app: springboot-cicd
  template:
    metadata:
      labels:
        app: springboot-cicd
    spec:
      containers:
      - name: springboot-cicd-container
        image: registry.tirzok.com:5000/springboot-cicd-dynamic:7-dynamic
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-cicd-svc
spec:
  type: NodePort
  selector:
    app: springboot-cicd
  ports:
  - port: 8080
    targetPort: 8080
